/*
 Copyright (c) 2026 John Talbot

 Authored by John Talbot, with substantial assistance from Anthropic's
 Claude and Google's Gemini. See the NOTICE file for details.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/


// Ensure Dependencies Loaded
if (typeof CayleyGraph === 'undefined') {
    console.error("cayley-graph.js not loaded!");
    alert("Error: cayley-graph.js failed to load.");
}

const { generateSubgroup, permToCycleString, detectS4A4, renderCayleyGraph, layoutCayleyGraph } = CayleyGraph;

const container = document.getElementById('graph-container');
const fallbackCanvas = document.getElementById('fallback-canvas');
const selector = document.getElementById('group-select');
const descEl = document.getElementById('group-description');
const legendEl = document.getElementById('legend');

// --------------------------------------------------
// Local 3D Rendering Logic (Independent of cayley-graph.js)
// --------------------------------------------------

let graph3DInstance = null;
let graph3DContainer = null;
let graph3DBackground = null;

function setup3DContainer(parent) {
    if (!graph3DBackground) {
        // Full-viewport dark background — stays at left:0 so it fills behind the panel
        graph3DBackground = document.createElement('div');
        graph3DBackground.style.position = 'fixed';
        graph3DBackground.style.top = '0';
        graph3DBackground.style.left = '0';
        graph3DBackground.style.width = '100vw';
        graph3DBackground.style.height = '100vh';
        graph3DBackground.style.zIndex = '-1';
        graph3DBackground.style.backgroundColor = '#0f172a';
        graph3DBackground.style.pointerEvents = 'none';
        graph3DBackground.style.display = 'none';
        document.body.appendChild(graph3DBackground);
    }
    if (!graph3DContainer) {
        // Hit-test container — positioned to match the visible graph area so hover is correct
        graph3DContainer = document.createElement('div');
        graph3DContainer.style.position = 'fixed';
        graph3DContainer.style.top = '0';
        graph3DContainer.style.left = '0';
        graph3DContainer.style.width = '100vw';
        graph3DContainer.style.height = '100vh';
        graph3DContainer.style.zIndex = '0';
        graph3DContainer.style.backgroundColor = 'transparent';
        document.body.appendChild(graph3DContainer);
    }
    return graph3DContainer;
}

// --------------------------------------------------
// Resize Handler
// --------------------------------------------------
function resizeCanvas() {
    const panelW = window.innerWidth > 640 ? 310 : 0;
    fallbackCanvas.width = window.innerWidth;
    fallbackCanvas.height = window.innerHeight;
    if (graph3DInstance) {
        graph3DInstance.width(window.innerWidth - panelW);
        graph3DInstance.height(window.innerHeight);
        if (graph3DContainer) {
            graph3DContainer.style.left = panelW + 'px';
            graph3DContainer.style.width = (window.innerWidth - panelW) + 'px';
        }
        // graph3DBackground stays full-width to cover behind the panel
    }
}
window.addEventListener('resize', resizeCanvas);
resizeCanvas();

// --------------------------------------------------
// Group Definitions
// --------------------------------------------------

// === Helper for Unicode Subscripts ===
function toSubscript(text) {
    const subs = {
        '0': '₀', '1': '₁', '2': '₂', '3': '₃', '4': '₄',
        '5': '₅', '6': '₆', '7': '₇', '8': '₈', '9': '₉'
    };
    return text.toString().split('').map(c => subs[c] || c).join('');
}

function toSuperscript(text) {
    const sups = {
        '0': '⁰', '1': '¹', '2': '²', '3': '³', '4': '⁴',
        '5': '⁵', '6': '⁶', '7': '⁷', '8': '⁸', '9': '⁹'
    };
    return text.toString().split('').map(c => sups[c] || c).join('');
}

const groups = {
    "C7": {
        name: "Cyclic Group C7",
        desc: "Generated by a single element of order 7. The Cayley graph is a simple C<sub>7</sub> cycle.",
        generators: [
            { p: [2, 3, 4, 5, 6, 7, 1], label: "a", color: "#38bdf8" } // (1 2 3 4 5 6 7)
        ]
    },
    "Q8": {
        name: "Quaternion Group Q8",
        desc: "Generated by i, j. Order 8. Q<sub>8</sub>.",
        generators: [
            { p: [3, 4, 2, 1, 8, 7, 5, 6], label: "i", color: "#38bdf8" }, // i
            { p: [5, 6, 7, 8, 2, 1, 4, 3], label: "j", color: "#f43f5e" }  // j
        ]
    },
    "D5": {
        name: "Dihedral Group D5",
        desc: "Symmetries of a pentagon. Generated by rotation r (order 5) and reflection s (order 2). D<sub>5</sub>.",
        generators: [
            { p: [2, 3, 4, 5, 1], label: "r", color: "#38bdf8" }, // (1 2 3 4 5)
            { p: [1, 5, 4, 3, 2], label: "s", color: "#f43f5e" }  // (2 5)(3 4)
        ]
    },
    "D5alt": {
        name: "Dihedral Group D5",
        desc: "Symmetries of a pentagon. Generated by two reflections. D₅.",
        generators: [
            { p: [1, 5, 4, 3, 2], label: "s" + toSubscript(1), color: "#38bdf8" }, // (2 5)(3 4)
            { p: [2, 1, 5, 4, 3], label: "s" + toSubscript(2), color: "#f43f5e" }  // (1 2)(5 4)
        ]
    },
    "C2xC2": {
        name: "Klein Four-Group (V4)",
        desc: "Isomorphic to C₂ × C₂. Generated by two commuting elements of order 2.",
        generators: [
            { p: [2, 1, 4, 3], label: "a", color: "#38bdf8" }, // (1 2)(3 4)
            { p: [3, 4, 1, 2], label: "b", color: "#f43f5e" }  // (1 3)(2 4)
        ]
    },
    "C2xC4": {
        name: "C2 x C4",
        desc: "The direct product of C₂ and C₄. Order 8.",
        generators: [
            { p: [2, 1, 3, 4, 5, 6], label: "a", color: "#38bdf8" }, // (1 2)
            { p: [1, 2, 4, 5, 6, 3], label: "b", color: "#f43f5e" }  // (3 4 5 6)
        ]
    },
    "D4": {
        name: "Dihedral Group D4",
        desc: "Symmetries of a square. Generated by rotation r (order 4) and reflection s (order 2).",
        generators: [
            { p: [2, 3, 4, 1], label: "r", color: "#38bdf8" }, // (1 2 3 4)
            { p: [4, 3, 2, 1], label: "s", color: "#f43f5e" }  // (1 4)(2 3)
        ]
    },
    "C2xC2xC2": {
        name: "C2 x C2 x C2",
        desc: "Elementary Abelian Group of order 8. Three independent generators of order 2. Forms a Q₃ cube graph.",
        generators: [
            { p: [2, 1, 3, 4, 5, 6], label: "a", color: "#ef4444" }, // Red-500
            { p: [1, 2, 4, 3, 5, 6], label: "b", color: "#10b981" }, // Emerald-500
            { p: [1, 2, 3, 4, 6, 5], label: "c", color: "#f59e0b" }  // Amber-500
        ]
    },
    "C2xC2xC2xC2": {
        name: "C2 x C2 x C2 x C2 (Hypercube)",
        desc: "Elementary Abelian Group of order 16. Four independent generators. Visualized as a Q<sub>4</sub> Cube inside a Cube (Tesseract).",
        generators: [
            { p: [2, 1, 3, 4, 5, 6, 7, 8], label: "a", color: "#38bdf8" }, // (1 2) 
            { p: [1, 2, 4, 3, 5, 6, 7, 8], label: "b", color: "#f43f5e" }, // (3 4)
            { p: [1, 2, 3, 4, 6, 5, 7, 8], label: "c", color: "#a3e635" }, // (5 6)
            { p: [1, 2, 3, 4, 5, 6, 8, 7], label: "d", color: "#fbbf24" }  // (7 8)
        ]
    },
    "A4": {
        name: "A4 (Cuboctahedron)",
        desc: "Generated by two 3-cycles.",
        generators: [
            { p: [2, 3, 1, 4], label: "(1 2 3)", color: "#22c55e" }, // Green
            { p: [1, 3, 4, 2], label: "(2 3 4)", color: "#f43f5e" }
        ]
    },
    // ... (rest of groups)

    "A4_Truncated": {
        name: "A4 (Truncated Tetrahedron)",
        desc: "Generated by a double transposition and a 3-cycle.",
        generators: [
            { p: [2, 1, 4, 3], label: "(1 2)(3 4)", color: "#22c55e" }, // Green
            { p: [2, 3, 1, 4], label: "(1 2 3)", color: "#f43f5e" }
        ]
    },
    "S4_Type1": {
        name: "S4 (Rhombicuboctahedron)",
        desc: "Generated by 3-cycle and 4-cycle.",
        generators: [
            { p: [2, 3, 1, 4], label: "(1 2 3)", color: "#22c55e" }, // Green
            { p: [2, 3, 4, 1], label: "(1 2 3 4)", color: "#f43f5e" }
        ]
    },
    "S4_Type4": {
        name: "S4 (Nauru Graph)",
        desc: "Generated by three intersecting2-cycles.",
        generators: [
            { p: [2, 1, 3, 4], label: "(1 2)", color: "#ef4444" }, // Red-500
            { p: [3, 2, 1, 4], label: "(1 3)", color: "#10b981" }, // Emerald-500
            { p: [4, 2, 3, 1], label: "(1 4)", color: "#f59e0b" }  // Amber-500
        ]
    },
    "S4_SingleGen": {
        name: "S4 (Disconnected: Single Generator)",
        desc: "Symmetric Group S₄ with just one generator. The graph decomposes into 6 disconnected 4-cycles (the cosets of the generated C₄).",
        baseGenerators: [
            { p: [2, 1, 3, 4] },
            { p: [2, 3, 4, 1] }
        ],
        generators: [
            { p: [2, 3, 4, 1], label: "(1 2 3 4)", color: "#38bdf8" }
        ]
    },
    "S4_Disconnected_V4": {
        name: "S4 (Disconnected: Two Transpositions)",
        desc: "Symmetric Group S₄ generated by two disjoint transpositions. The graph decomposes into 6 disconnected squares.",
        baseGenerators: [
            { p: [2, 1, 3, 4] },
            { p: [2, 3, 4, 1] }
        ],
        generators: [
            { p: [2, 1, 3, 4], label: "(1 2)", color: "#ef4444" },
            { p: [1, 2, 4, 3], label: "(3 4)", color: "#38bdf8" }
        ]
    },
    "S4_Disconnected_A4": {
        name: "S4 (Disconnected: Two 3-cycles)",
        desc: "Symmetric Group S₄ generated by two 3-cycles. Since 3-cycles are even permutations, they only generate the alternating group A₄. The graph decomposes into two disconnected components (the even and odd permutations).",
        baseGenerators: [
            { p: [2, 1, 3, 4] },
            { p: [2, 3, 4, 1] }
        ],
        generators: [
            { p: [2, 3, 1, 4], label: "(1 2 3)", color: "#22c55e" },
            { p: [1, 3, 4, 2], label: "(2 3 4)", color: "#f43f5e" }
        ]
    },
    "S4_Permutohedron": {
        name: "S4 (Permutohedron)",
        desc: "Generated by adjacent transpositions. Vertices form a Truncated Octahedron.",
        generators: [
            { p: [2, 1, 3, 4], label: "(1 2)", color: "#ef4444" }, // Red-500
            { p: [1, 3, 2, 4], label: "(2 3)", color: "#10b981" }, // Emerald-500
            { p: [1, 2, 4, 3], label: "(3 4)", color: "#f59e0b" }  // Amber-500
        ]
    },
    "S4_TruncatedCube": {
        name: "S4 (Truncated Cube)",
        desc: "Generated by 2-cycle and 3-cycle.",
        generators: [
            { p: [2, 1, 3, 4], label: "(1 2)", color: "#22c55e" }, // Green
            { p: [1, 3, 4, 2], label: "(2 3 4)", color: "#f43f5e" } // 3-cycle
        ]
    },
    "A5": {
        name: "Alternating Group A5 (Truncated Icosahedron)",
        desc: "The smallest non-abelian simple group. Order 60. Generated by a double transposition (order 2) and a 5-cycle (order 5). Its Cayley graph is a truncated icosahedron.",
        generators: [
            { p: [2, 1, 4, 3, 5], label: "(1 2)(3 4)", color: "#ef4444" }, // (1 2)(3 4)
            { p: [2, 3, 4, 5, 1], label: "(1 2 3 4 5)", color: "#10b981" }  // (1 2 3 4 5)
        ]
    },
    "A5_SingleGen": {
        name: "A5 (Disconnected: Single 5-cycle)",
        desc: "Alternating Group A₅ with just one 5-cycle generator. Decomposes into 12 disconnected 5-cycles (pentagons).",
        baseGenerators: [
            { p: [2, 1, 4, 3, 5] },
            { p: [2, 3, 4, 5, 1] }
        ],
        generators: [
            { p: [2, 3, 4, 5, 1], label: "(1 2 3 4 5)", color: "#10b981" }
        ]
    },
    "A5_Disconnected_A4": {
        name: "A5 (Disconnected: A4 subgraphs)",
        desc: "Alternating Group A₅ generated by two 3-cycles. These generate A₄, so the graph cleanly decomposes into 5 disconnected A₄ Cayley graphs (Cuboctahedra).",
        baseGenerators: [
            { p: [2, 1, 4, 3, 5] },
            { p: [2, 3, 4, 5, 1] }
        ],
        generators: [
            { p: [2, 3, 1, 4, 5], label: "(1 2 3)", color: "#22c55e" },
            { p: [1, 3, 4, 2, 5], label: "(2 3 4)", color: "#f43f5e" }
        ]
    },
    "S5": {
        name: "Symmetric Group S5",
        desc: "The symmetric group on 5 elements. Order 120. Cayley graph has 120 nodes.",
        generators: [
            { p: [2, 1, 3, 4, 5], label: "(1 2)", color: "#ef4444" },
            { p: [2, 3, 4, 5, 1], label: "(1 2 3 4 5)", color: "#38bdf8" }
        ]
    },
    "S5_SingleGen": {
        name: "S5 (Disconnected: Single 5-cycle)",
        desc: "Symmetric Group S₅ with just one generator. The graph decomposes into 24 disconnected 5-cycles (the cosets of the generated C₅).",
        baseGenerators: [
            { p: [2, 1, 3, 4, 5] },
            { p: [2, 3, 4, 5, 1] }
        ],
        generators: [
            { p: [2, 3, 4, 5, 1], label: "(1 2 3 4 5)", color: "#38bdf8" }
        ]
    },
    "S5_Disconnected_S4": {
        name: "S5 (Disconnected: S4 subgraphs)",
        desc: "Symmetric Group S₅ generated by permutations that fix the 5th element. The generated subgroup is S₄, so the graph cleanly decomposes into 5 disconnected S₄ Cayley graphs.",
        baseGenerators: [
            { p: [2, 1, 3, 4, 5] },
            { p: [2, 3, 4, 5, 1] }
        ],
        generators: [
            { p: [2, 1, 3, 4, 5], label: "(1 2)", color: "#ef4444" },
            { p: [2, 3, 4, 1, 5], label: "(1 2 3 4)", color: "#38bdf8" }
        ]
    },
    "S6": {
        name: "Symmetric Group S6",
        desc: "The symmetric group on 6 elements. Order 720. Cayley graph has 720 nodes.",
        generators: [
            { p: [2, 1, 3, 4, 5, 6], label: "(1 2)", color: "#ef4444" },
            { p: [2, 3, 4, 5, 6, 1], label: "(1 2 3 4 5 6)", color: "#38bdf8" }
        ]
    },
    "C10xC5": {
        name: "C10 x C5",
        desc: "Direct product of C₁₀ and C₅. This is an Abelian group of order 50. Its Cayley graph is a 10x5 grid wrapped around a torus.",
        generators: [
            { p: [2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 12, 13, 14, 15, 16, 17, 18, 19, 20, 11, 22, 23, 24, 25, 26, 27, 28, 29, 30, 21, 32, 33, 34, 35, 36, 37, 38, 39, 40, 31, 42, 43, 44, 45, 46, 47, 48, 49, 50, 41], label: "a", color: "#38bdf8" }, // 5 cycles of length 10
            { p: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], label: "b", color: "#f43f5e" }  // 10 cycles of length 5? No, this is 10 shifts of 5.
        ]
    }
};

function layoutHypercube(elements, multiplicationTable) {
    // Generators a, b, c form the cube structure. d shifts between inner/outer.
    // Assume gen[0]=a (x), gen[1]=b (y), gen[2]=c (z), gen[3]=d (w)

    // 1. Identify "Inner Cube" Subgroup <a, b, c>
    const subGens = [0, 1, 2];
    const innerNodes = new Set();
    const queue = [0];
    innerNodes.add(0);

    let head = 0;
    while (head < queue.length) {
        const u = queue[head++];
        subGens.forEach(gIdx => {
            const v = multiplicationTable[gIdx][u];
            if (!innerNodes.has(v)) {
                innerNodes.add(v);
                queue.push(v);
            }
        });
    }

    // 2. Assign coordinates
    const positions = new Array(elements.length);
    const coords = new Map(); // id -> {x, y, z}

    // BFS for coords on inner cube
    const qWithCoords = [{ id: 0, x: -1, y: -1, z: -1 }];
    coords.set(0, { x: -1, y: -1, z: -1 });
    head = 0;

    while (head < qWithCoords.length) {
        const { id, x, y, z } = qWithCoords[head++];

        // Generator 0 (a) -> flips x
        const va = multiplicationTable[0][id];
        if (!coords.has(va)) {
            const newC = { x: -x, y: y, z: z };
            coords.set(va, newC);
            qWithCoords.push({ id: va, ...newC });
        }

        // Generator 1 (b) -> flips y
        const vb = multiplicationTable[1][id];
        if (!coords.has(vb)) {
            const newC = { x: x, y: -y, z: z };
            coords.set(vb, newC);
            qWithCoords.push({ id: vb, ...newC });
        }

        // Generator 2 (c) -> flips z
        const vc = multiplicationTable[2][id];
        if (!coords.has(vc)) {
            const newC = { x: x, y: y, z: -z };
            coords.set(vc, newC);
            qWithCoords.push({ id: vc, ...newC });
        }
    }

    // 3. Set positions
    const R_in = 20;
    const R_out = 50;

    // Outer nodes: d * innerNode
    // d is generator 3
    const mapD = multiplicationTable[3];

    for (let i = 0; i < elements.length; i++) {
        if (innerNodes.has(i)) {
            // Inner Cube
            const c = coords.get(i);
            if (c) {
                positions[i] = {
                    fx: c.x * R_in,
                    fy: c.y * R_in,
                    fz: c.z * R_in
                };
            }
        } else {
            // Outer Cube
            const neighbor = mapD[i];
            if (innerNodes.has(neighbor)) {
                const c = coords.get(neighbor);
                if (c) {
                    positions[i] = {
                        fx: c.x * R_out,
                        fy: c.y * R_out,
                        fz: c.z * R_out
                    };
                }
            }
        }
    }

    return positions;
}

function layoutC2xC4(elements, table) {
    const n = elements.length;
    const positions = new Array(n);
    const coords = new Map();
    const cycle = [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 1, y: 1 }, { x: 0, y: 1 }];
    const queue = [{ id: 0, z: 0, idx4: 0 }];
    coords.set(0, { z: 0, idx4: 0 });
    let head = 0;
    while (head < queue.length) {
        const { id, z, idx4 } = queue[head++];
        const v0 = table[0][id];
        if (!coords.has(v0)) {
            const next = { z: 1 - z, idx4: idx4 };
            coords.set(v0, next);
            queue.push({ id: v0, ...next });
        }
        const v1 = table[1][id];
        if (!coords.has(v1)) {
            const next = { z: z, idx4: (idx4 + 1) % 4 };
            coords.set(v1, next);
            queue.push({ id: v1, ...next });
        }
    }
    const S = 60;
    for (let i = 0; i < n; i++) {
        const c = coords.get(i) || { z: 0, idx4: 0 };
        const xy = cycle[c.idx4];
        positions[i] = { fx: (xy.x - 0.5) * S * 2, fy: (xy.y - 0.5) * S * 2, fz: (c.z - 0.5) * S * 2 };
    }
    return positions;
}


function layoutTorus(elements, table, n_rows, n_cols) {
    const n = elements.length;
    const positions = new Array(n);
    const coords = new Map();

    const queue = [{ id: 0, r: 0, c: 0 }];
    coords.set(0, { r: 0, c: 0 });
    let head = 0;
    while (head < queue.length) {
        const { id, r, c } = queue[head++];

        // Gen 0 (a) -> step in rows (10)
        const v0 = table[0][id];
        if (!coords.has(v0)) {
            const next = { r: (r + 1) % n_rows, c: c };
            coords.set(v0, next);
            queue.push({ id: v0, ...next });
        }

        // Gen 1 (b) -> step in columns (5)
        const v1 = table[1][id];
        if (!coords.has(v1)) {
            const next = { r: r, c: (c + 1) % n_cols };
            coords.set(v1, next);
            queue.push({ id: v1, ...next });
        }
    }

    const R = 80; // Major radius
    const r_minor = 25; // Minor radius

    for (let i = 0; i < n; i++) {
        const c = coords.get(i) || { r: 0, c: 0 };
        const phi = (c.r / n_rows) * 2 * Math.PI;
        const theta = (c.c / n_cols) * 2 * Math.PI;

        positions[i] = {
            fx: (R + r_minor * Math.cos(theta)) * Math.cos(phi),
            fy: (R + r_minor * Math.cos(theta)) * Math.sin(phi),
            fz: r_minor * Math.sin(theta)
        };
    }
    return positions;
}

// --------------------------------------------------
// Permutohedron Layout (Truncated Octahedron)
// --------------------------------------------------
function layoutPermutohedron(elements, multiplicationTable) {
    // Vertices: Permutations of (0, +/-1, +/-2).
    // Total 24 vertices.

    // 1. Generate Vertices of Truncated Octahedron
    // Scale: 1 unit.
    // Base permutation: (0, 1, 2). Extended with signs.
    // 0 is fixed-ish.
    // Actually standard permutohedron of S4 is convex hull of (1, 2, 3, 4).
    // In 3D subspace x+y+z+w=10 -> project to 3D.
    // Coordinate set (0, 1, 2) plus signs gives 24 points.
    // (0, +/-1, +/-2) is valid.

    const geomVerts = [];
    // Generate all permutations of [0, 1, 2] with signs for 1 and 2
    const baseCoords = [0, 1, 2];
    const perms = [
        [0, 1, 2], [0, 2, 1], [1, 0, 2], [1, 2, 0], [2, 0, 1], [2, 1, 0]
    ];

    perms.forEach(p => {
        // For each p, 0 is at p[0]=0 position? No, values are 0, 1, 2.
        // We take the values. Length is 3?
        // Wait, Truncated Octahedron has 24 vertices.
        // It's permutations of (+/-1, +/-2, 0).
        // 0 has no sign. 1 and 2 have 2 signs each.
        // positions of 0: 3 choices (x, y, z).
        // 1 and 2 take other 2.
        // signs of 1, 2: 4 choices.
        // Total 3 * 2 * 4 = 24.

        // Loop x, y, z from -2 to 2
    });

    // Easier generation loop
    for (let x = -2; x <= 2; x++) {
        for (let y = -2; y <= 2; y++) {
            for (let z = -2; z <= 2; z++) {
                const abs = [Math.abs(x), Math.abs(y), Math.abs(z)].sort((a, b) => a - b);
                if (abs[0] === 0 && abs[1] === 1 && abs[2] === 2) {
                    geomVerts.push({ x, y, z });
                }
            }
        }
    }

    // 2. Build Geometric Adjacency
    // Distance = sqrt(2) approx. (e.g. (0,1,2) to (0,2,1) distSq = 1+1=2)
    const geomAdj = geomVerts.map(() => []);
    const geomEdgeType = geomVerts.map(() => []); // [neighborIdx] -> 'square' | 'hex'

    for (let i = 0; i < geomVerts.length; i++) {
        for (let j = i + 1; j < geomVerts.length; j++) {
            const dx = geomVerts[i].x - geomVerts[j].x;
            const dy = geomVerts[i].y - geomVerts[j].y;
            const dz = geomVerts[i].z - geomVerts[j].z;
            const d2 = dx * dx + dy * dy + dz * dz;
            if (Math.abs(d2 - 2) < 0.1) {
                geomAdj[i].push(j);
                geomAdj[j].push(i);
            }
        }
    }

    // 3. Classify Geometric Edges
    // An edge (u, v) is 'square' if it is part of a 4-cycle.
    // In Truncated Octahedron, Square faces are 4-cycles. Hex are 6.
    // There are NO 3-cycles.
    // If an edge is on a Square face, it is part of EXACTLY ONE 4-cycle?
    // Yes. Squares are isolated by Hexagons.
    // So if dist(u, v)=1, check if they share a common neighbor w at dist=1? No, 3-cycle.
    // Check if they form u-v-w-z-u.
    // i.e. do u and v share a neighbor-of-neighbor at dist 1?
    // Common neighbors of u and v? None (no triangles).
    // Paths of length 3 between u and v?
    // u-x-y-v.
    // If such path exists, u-v is part of 4-cycle.

    // For each edge (u, v), check if there exists x in Adj[u], y in Adj[v] such that x, y are adjacent (and x!=v, y!=u).
    for (let i = 0; i < geomVerts.length; i++) {
        geomEdgeType[i] = new Array(geomAdj[i].length).fill('hex'); // Default to hex-only

        for (let k = 0; k < geomAdj[i].length; k++) {
            const neighbor = geomAdj[i][k];
            // Check for 4-cycle
            let isSquare = false;
            const Ni = geomAdj[i];
            const Nj = geomAdj[neighbor];

            // Check if any n1 in Ni connects to any n2 in Nj
            for (let n1 of Ni) {
                if (n1 === neighbor) continue;
                for (let n2 of Nj) {
                    if (n2 === i) continue;
                    // Are n1 and n2 connected?
                    if (geomAdj[n1].includes(n2)) {
                        isSquare = true;
                        break;
                    }
                }
                if (isSquare) break;
            }

            if (isSquare) geomEdgeType[i][k] = 'square';
        }
    }

    // 4. Backtracking Solver
    // Map S4 elements -> Geom Indices
    const N = elements.length;
    let assignment = new Int32Array(N).fill(-1);
    let usedGeom = new Int8Array(geomVerts.length).fill(0);

    const mapA = multiplicationTable[0];
    const mapB = multiplicationTable[1];
    const mapC = multiplicationTable[2];

    // Order nodes by BFS for locality
    const order = [];
    const visited = new Int8Array(N).fill(0);
    const q = [0];
    visited[0] = 1;
    while (q.length) {
        const u = q.shift();
        order.push(u);
        const nexts = [mapA[u], mapB[u], mapC[u]];
        for (let v of nexts) {
            if (!visited[v]) {
                visited[v] = 1;
                q.push(v);
            }
        }
    }

    function solve(idx) {
        if (idx >= N) return true;
        const u = order[idx];

        // If already assigned by parent (shouldn't happen in strict tree order, but graph has cycles)
        if (assignment[u] !== -1) return solve(idx + 1);

        // Filter candidates based on assigned neighbors
        // Neighbors in graph:
        const pa = mapA[u]; // neighbor via a
        const pb = mapB[u]; // neighbor via b
        const pc = mapC[u]; // neighbor via c

        // Identify geometric constraints from assigned neighbors
        let constraints = []; // { geomIdx, edgeType }

        // Edge u-pa is type 'a' -> SQUARE geometric edge
        if (assignment[pa] !== -1) constraints.push({ g: assignment[pa], type: 'square' });
        // Edge u-pb is type 'b' -> HEX geometric edge
        if (assignment[pb] !== -1) constraints.push({ g: assignment[pb], type: 'hex' });
        // Edge u-pc is type 'c' -> SQUARE geometric edge
        if (assignment[pc] !== -1) constraints.push({ g: assignment[pc], type: 'square' });

        // Candidates:
        // If constraints exist, candidates are common neighbors of constraint nodes.
        // If no constraints (start node), all unused.

        let candidates = [];
        if (constraints.length === 0) {
            // Pick a fixed start node to break symmetry?
            // (1, 2, 0)
            const startId = geomVerts.findIndex(v => v.x === 1 && v.y === 2 && v.z === 0);
            if (!usedGeom[startId]) candidates = [startId];
            // If start is taken, we fail (shouldn't happen for node 0)
        } else {
            // Find candidates satisfying ALL constraints
            // Start with neighbors of first constraint
            const firstC = constraints[0];
            const neighbors = geomAdj[firstC.g];

            for (let cand of neighbors) {
                if (usedGeom[cand]) continue;

                // Check all constraints
                let ok = true;
                for (let c of constraints) {
                    // cand must be neighbor of c.g
                    const nIdx = geomAdj[c.g].indexOf(cand);
                    if (nIdx === -1) { ok = false; break; }

                    // Edge type check
                    const eType = geomEdgeType[c.g][nIdx];
                    if (eType !== c.type) { ok = false; break; }
                }

                if (ok) candidates.push(cand);
            }
        }

        // Try candidates
        for (let cand of candidates) {
            assignment[u] = cand;
            usedGeom[cand] = 1;

            // Forward checking / Lookahead? 
            // Minimal lookahead: Check if placing u here makes it impossible to place unassigned neighbors?
            // S4 is small, maybe not needed.

            if (solve(idx + 1)) return true;

            usedGeom[cand] = 0;
            assignment[u] = -1;
        }

        return false;
    }

    if (!solve(0)) {
        console.error("Permutohedron layout failed to find isomorphism.");
        // Fallback or partial
        return null;
    }

    // Output
    const R = 30;
    const output = new Array(N);
    for (let i = 0; i < N; i++) {
        const v = geomVerts[assignment[i]];
        output[i] = { fx: v.x * R, fy: v.y * R, fz: v.z * R };
    }
    return output;
}

// --------------------------------------------------
// Truncated Tetrahedron Layout (A4)
// --------------------------------------------------
function layoutTruncatedTetrahedron(elements, multiplicationTable) {
    // Generators: a (order 2), b (order 3).
    // The cosets of <b> (order 3) form the vertices of the tetrahedron.

    // 1. Identify Cosets of <b>
    const genB_idx = 1; // 3-cycle
    const mapB = multiplicationTable[genB_idx];
    const N = elements.length;
    const visited = new Array(N).fill(false);
    const cosets = [];

    for (let i = 0; i < N; i++) {
        if (!visited[i]) {
            const coset = [i];
            visited[i] = true;
            let curr = i;
            while (true) {
                const next = mapB[curr];
                if (next === i) break;
                coset.push(next);
                visited[next] = true;
                curr = next;
            }
            cosets.push(coset);
        }
    }

    if (cosets.length !== 4) {
        console.warn("Truncated Tetrahedron Layout: Expected 4 cosets, found", cosets.length);
        return null;
    }

    // 2. Build Adjacency of Cosets via 'a'
    const genA_idx = 0;
    const mapA = multiplicationTable[genA_idx];
    const cosetAdj = Array.from({ length: 4 }, () => new Set());

    cosets.forEach((C_i, i) => {
        C_i.forEach(u => {
            const v = mapA[u];
            const j = cosets.findIndex(C => C.includes(v));
            if (j !== -1 && j !== i) {
                cosetAdj[i].add(j);
                cosetAdj[j].add(i);
            }
        });
    });

    // 3. Assign Tetrahedron Coordinates to Cosets
    // Vertices of regular tetrahedron: (1,1,1), (1,-1,-1), (-1,1,-1), (-1,-1,1)
    const tetraVerts = [
        { x: 1, y: 1, z: 1 },
        { x: 1, y: -1, z: -1 },
        { x: -1, y: 1, z: -1 },
        { x: -1, y: -1, z: 1 }
    ];

    // BFS to assign unique tetra vertex to each coset
    const cosetMap = new Array(4).fill(-1);
    const assignedVerts = new Array(4).fill(false);

    // Assign coset 0 to vertex 0
    cosetMap[0] = 0;
    assignedVerts[0] = true;

    // Simple greedy assignment for neighbors
    // Since it's a complete graph (K4) on cosets?
    // A4 on 4 cosets acts like A4 on 4 points?
    // Actually yes, the cosets correspond to the 4 items permuted.
    // Any bijection works as long as we respect neighbor structure.

    const queue = [0];
    while (queue.length > 0) {
        const u = queue.shift();
        const neighbors = Array.from(cosetAdj[u]);
        neighbors.forEach(v => {
            if (cosetMap[v] === -1) {
                // Pick first available vertex
                const av = assignedVerts.findIndex(x => !x);
                if (av !== -1) {
                    cosetMap[v] = av;
                    assignedVerts[av] = true;
                    queue.push(v);
                }
            }
        });
    }

    // 4. Position Nodes
    const positions = new Array(N);
    const R = 80;
    const offset = 35;

    cosets.forEach((nodes, cIdx) => {
        const vIdx = cosetMap[cIdx];
        const center = tetraVerts[vIdx];
        const cx = center.x * R;
        const cy = center.y * R;
        const cz = center.z * R;

        nodes.forEach(u => {
            const v = mapA[u];
            const neighborCosetIdx = cosets.findIndex(C => C.includes(v));
            const neighborVIdx = cosetMap[neighborCosetIdx];

            let fx = cx, fy = cy, fz = cz;

            if (neighborVIdx !== undefined) {
                const neighborCenter = tetraVerts[neighborVIdx];
                const dx = neighborCenter.x - center.x;
                const dy = neighborCenter.y - center.y;
                const dz = neighborCenter.z - center.z;

                // Normalize and scale offset
                const len = Math.sqrt(dx * dx + dy * dy + dz * dz);
                fx += (dx / len) * offset;
                fy += (dy / len) * offset;
                fz += (dz / len) * offset;
            }

            positions[u] = { fx, fy, fz };
        });
    });

    return positions;
}

// --------------------------------------------------
// Truncated Cube Layout
// --------------------------------------------------
function layoutTruncatedCube(elements, multiplicationTable) {
    // Generators: a (order 2), b (order 3).
    // Identify 8 cosets of <b> (order 3 subgroups).
    // These 8 cosets correspond to the corners of a Cube.

    // 1. Identify Cosets of <b>
    const genB_idx = 1; // 3-cycle
    const mapB = multiplicationTable[genB_idx];
    const N = elements.length;
    const visited = new Array(N).fill(false);
    const cosets = []; // Array of arrays (size 3)

    for (let i = 0; i < N; i++) {
        if (!visited[i]) {
            const coset = [i];
            visited[i] = true;
            let curr = i;
            while (true) {
                const next = mapB[curr];
                if (next === i) break;
                coset.push(next);
                visited[next] = true;
                curr = next;
            }
            cosets.push(coset);
        }
    }

    if (cosets.length !== 8) {
        console.warn("Truncated Cube Layout: Expected 8 cosets, found", cosets.length);
        return null; // Fallback
    }

    // 2. Build Adjacency Graph of Cosets (via generator a)
    const genA_idx = 0;
    const mapA = multiplicationTable[genA_idx];
    const cosetAdj = Array.from({ length: 8 }, () => new Set());

    cosets.forEach((C_i, i) => {
        C_i.forEach(u => {
            const v = mapA[u];
            // Find which coset v belongs to
            const j = cosets.findIndex(C => C.includes(v));
            if (j !== -1 && j !== i) {
                cosetAdj[i].add(j);
                cosetAdj[j].add(i);
            }
        });
    });

    // 3. Layout Cosets as Cube
    // Use rigid structure identification:
    // 0 (000) -> Neighbors 1(100), 2(010), 4(001)
    // Common(1,2) -> 3(110)
    // Common(1,4) -> 5(101)
    // Common(2,4) -> 6(011)
    // Common(3,5,6) -> 7(111)

    const cosetPos = new Map();
    const c0 = 0; // Start with identity coset
    cosetPos.set(c0, { x: -1, y: -1, z: -1 }); // 000

    const neighbors0 = Array.from(cosetAdj[c0]);
    if (neighbors0.length < 3) {
        console.warn("Truncated Cube: Coset 0 has degree < 3");
        return null;
    }

    const c1 = neighbors0[0]; // 100
    const c2 = neighbors0[1]; // 010
    const c4 = neighbors0[2]; // 001

    cosetPos.set(c1, { x: 1, y: -1, z: -1 });
    cosetPos.set(c2, { x: -1, y: 1, z: -1 });
    cosetPos.set(c4, { x: -1, y: -1, z: 1 });

    // Find c3: Common neighbor of c1 and c2 (not c0)
    const n1 = new Set(cosetAdj[c1]);
    const n2 = new Set(cosetAdj[c2]);
    let c3 = -1;
    for (let x of n1) {
        if (n2.has(x) && x !== c0) { c3 = x; break; }
    }
    if (c3 !== -1) cosetPos.set(c3, { x: 1, y: 1, z: -1 }); // 110

    // Find c5: Common neighbor of c1 and c4 (not c0)
    const n4 = new Set(cosetAdj[c4]);
    let c5 = -1;
    for (let x of n1) {
        if (n4.has(x) && x !== c0) { c5 = x; break; }
    }
    if (c5 !== -1) cosetPos.set(c5, { x: 1, y: -1, z: 1 }); // 101

    // Find c6: Common neighbor of c2 and c4 (not c0)
    let c6 = -1;
    for (let x of n2) {
        if (n4.has(x) && x !== c0) { c6 = x; break; }
    }
    if (c6 !== -1) cosetPos.set(c6, { x: -1, y: 1, z: 1 }); // 011

    // Find c7: Common neighbor of c3, c5, c6
    // Or just remaining node along diagonal
    let c7 = -1;
    if (c3 !== -1) {
        const n3 = new Set(cosetAdj[c3]);
        for (let x of n3) {
            if (x !== c1 && x !== c2) { c7 = x; break; }
        }
    }
    if (c7 !== -1) cosetPos.set(c7, { x: 1, y: 1, z: 1 }); // 111

    // 4. Assign Final Node Positions
    const positions = new Array(N);
    const R = 45; // Cube Radius
    const r = 15; // Truncation offset

    cosets.forEach((nodes, cIdx) => {
        const center = cosetPos.get(cIdx) || { x: 0, y: 0, z: 0 };
        const cx = center.x * R;
        const cy = center.y * R;
        const cz = center.z * R;

        nodes.forEach(u => {
            const v = mapA[u];
            const neighborCosetIdx = cosets.findIndex(C => C.includes(v));
            const neighborCenter = cosetPos.get(neighborCosetIdx);

            let fx = cx, fy = cy, fz = cz;

            if (neighborCenter) {
                const dx = (neighborCenter.x - center.x) * r;
                const dy = (neighborCenter.y - center.y) * r;
                const dz = (neighborCenter.z - center.z) * r;

                fx += dx * 0.5; // Halfway vector approx
                fy += dy * 0.5;
                fz += dz * 0.5;
            }
            positions[u] = { fx, fy, fz };
        });
    });

    return positions;
}

// --------------------------------------------------
// Nauru Graph Layout (S4 Type 4)
// --------------------------------------------------
function layoutNauru(elements, multiplicationTable) {
    // S4 Type 4 (Nauru Graph)
    // Isomorphic to Generalized Petersen Graph G(12, 5).
    // Embedding: 12-pointed star inside 12-gon.

    // 1. Construct Target Graph G(12, 5)
    // Nodes 0..23.
    // 0..11: Outer u_i
    // 12..23: Inner v_i
    const targetAdj = Array.from({ length: 24 }, () => []);
    for (let i = 0; i < 12; i++) {
        const u = i;
        const v = i + 12;
        const u_next = (i + 1) % 12;
        const u_prev = (i + 11) % 12;
        const v_next = 12 + (i + 5) % 12;
        const v_prev = 12 + (i + 7) % 12;

        targetAdj[u] = [u_next, u_prev, v];
        targetAdj[v] = [v_next, v_prev, u];
    }

    // 2. Find Isomorphism S4 -> G(12, 5)
    const N = 24;
    const mapping = new Int32Array(N).fill(-1);
    const used = new Int8Array(N).fill(0);
    mapping[0] = 0; used[0] = 1;

    const mapA = multiplicationTable[0];
    const mapB = multiplicationTable[1];
    const mapC = multiplicationTable[2];

    const bfsOrder = [];
    const q = [0];
    const visited = new Int8Array(N).fill(0);
    visited[0] = 1;

    while (q.length) {
        const u = q.shift();
        bfsOrder.push(u);
        const nexts = [mapA[u], mapB[u], mapC[u]];
        for (let v of nexts) {
            if (!visited[v]) {
                visited[v] = 1;
                q.push(v);
            }
        }
    }

    function solve(idx) {
        if (idx >= N) return true;
        const u = bfsOrder[idx];
        const neighbors = [mapA[u], mapB[u], mapC[u]].filter(n => mapping[n] !== -1);

        let candidates = [];
        if (neighbors.length === 0) {
            candidates = targetAdj.map((_, i) => i).filter(i => !used[i]);
        } else {
            const c1 = mapping[neighbors[0]];
            const startCands = targetAdj[c1];
            for (let cand of startCands) {
                if (used[cand]) continue;
                let ok = true;
                for (let i = 1; i < neighbors.length; i++) {
                    const c = mapping[neighbors[i]];
                    if (!targetAdj[cand].includes(c)) { ok = false; break; }
                }
                if (ok) candidates.push(cand);
            }
        }

        for (let cand of candidates) {
            mapping[u] = cand;
            used[cand] = 1;
            if (solve(idx + 1)) return true;
            used[cand] = 0;
            mapping[u] = -1;
        }
        return false;
    }

    if (!solve(1)) {
        console.warn("Nauru Layout: Isomorphism failed");
        return null;
    }

    // 3. Assign 2D Coordinates
    const positions = new Array(N);
    const R = 120; // Outer
    const r = 60;  // Inner

    for (let i = 0; i < N; i++) {
        const u = i;
        const gIdx = mapping[u];

        // u_k (Outer) if gIdx < 12
        // v_k (Inner) if gIdx >= 12
        const isOuter = (gIdx < 12);
        const k = isOuter ? gIdx : (gIdx - 12);

        // Angle: Start at -90deg (top)
        const angle = (k / 12) * Math.PI * 2 - Math.PI / 2;
        const rad = isOuter ? R : r;

        const px = rad * Math.cos(angle);
        const py = rad * Math.sin(angle);
        const pz = 0;

        positions[u] = { fx: px, fy: py, fz: pz };
    }

    return positions;
}

// --------------------------------------------------
// S5 Layout: Nested Truncated Icosahedra
// --------------------------------------------------
function layoutS5(elements, multiplicationTable) {
    const phi = (1 + Math.sqrt(5)) / 2;
    const geomVerts = [];
    const perms = [[0, 1, 2], [1, 2, 0], [2, 0, 1]];
    const base1 = [0, 1, 3 * phi];
    perms.forEach(p => {
        const x_base = base1[p[0]];
        const y_base = base1[p[1]];
        const z_base = base1[p[2]];
        [1, -1].forEach(s1 => {
            [1, -1].forEach(s2 => {
                const v = { x: x_base, y: y_base, z: z_base };
                if (v.x === 0) { v.y *= s1; v.z *= s2; }
                else if (v.y === 0) { v.x *= s1; v.z *= s2; }
                else if (v.z === 0) { v.x *= s1; v.y *= s2; }
                geomVerts.push(v);
            });
        });
    });
    const base2 = [1, 2 + phi, 2 * phi];
    perms.forEach(p => {
        const x_base = base2[p[0]];
        const y_base = base2[p[1]];
        const z_base = base2[p[2]];
        [1, -1].forEach(sx => {
            [1, -1].forEach(sy => {
                [1, -1].forEach(sz => {
                    geomVerts.push({ x: x_base * sx, y: y_base * sy, z: z_base * sz });
                });
            });
        });
    });
    const base3 = [2, 1 + 2 * phi, phi];
    perms.forEach(p => {
        const x_base = base3[p[0]];
        const y_base = base3[p[1]];
        const z_base = base3[p[2]];
        [1, -1].forEach(sx => {
            [1, -1].forEach(sy => {
                [1, -1].forEach(sz => {
                    geomVerts.push({ x: x_base * sx, y: y_base * sy, z: z_base * sz });
                });
            });
        });
    });

    let minDistSq = Infinity;
    for (let i = 0; i < geomVerts.length; i++) {
        for (let j = i + 1; j < geomVerts.length; j++) {
            const d2 = Math.pow(geomVerts[i].x - geomVerts[j].x, 2) +
                Math.pow(geomVerts[i].y - geomVerts[j].y, 2) +
                Math.pow(geomVerts[i].z - geomVerts[j].z, 2);
            if (d2 < minDistSq) minDistSq = d2;
        }
    }

    const geomAdj = geomVerts.map(() => []);
    for (let i = 0; i < geomVerts.length; i++) {
        for (let j = 0; j < geomVerts.length; j++) {
            if (i === j) continue;
            const d2 = Math.pow(geomVerts[i].x - geomVerts[j].x, 2) +
                Math.pow(geomVerts[i].y - geomVerts[j].y, 2) +
                Math.pow(geomVerts[i].z - geomVerts[j].z, 2);
            if (Math.abs(d2 - minDistSq) < 0.1) {
                geomAdj[i].push(j);
            }
        }
    }

    const isPentagonal = geomVerts.map(edges => new Array(geomAdj[geomVerts.indexOf(edges)].length).fill(false));
    function has5Cycle(u, v) {
        const q = [{ node: v, path: [u, v] }];
        while (q.length > 0) {
            const { node, path } = q.shift();
            if (path.length === 5) {
                if (geomAdj[node].includes(u)) return true;
                continue;
            }
            for (let next of geomAdj[node]) {
                if (path.includes(next)) continue;
                q.push({ node: next, path: [...path, next] });
            }
        }
        return false;
    }
    for (let i = 0; i < geomVerts.length; i++) {
        for (let k = 0; k < geomAdj[i].length; k++) {
            if (has5Cycle(i, geomAdj[i][k])) {
                isPentagonal[i][k] = true;
            }
        }
    }

    const N = elements.length;
    const mapA = multiplicationTable[0]; // (1 2)
    const mapB = multiplicationTable[1]; // (1 2 3 4 5)

    const b2 = new Int32Array(N);
    const b3 = new Int32Array(N);
    for (let i = 0; i < N; i++) b2[i] = mapB[mapB[i]];
    for (let i = 0; i < N; i++) b3[i] = b2[mapB[i]];

    const mapAPrime = new Int32Array(N);
    for (let i = 0; i < N; i++) {
        mapAPrime[i] = mapA[b2[mapA[b3[i]]]];
    }

    const parity = new Int8Array(N).fill(-1);
    const qParity = [0];
    parity[0] = 0;
    while (qParity.length) {
        const u = qParity.shift();
        const nexts = [mapA[u], mapB[u]];
        const steps = [1, 0];
        for (let j = 0; j < 2; j++) {
            const v = nexts[j];
            if (v !== undefined && parity[v] === -1) {
                parity[v] = (parity[u] + steps[j]) % 2;
                qParity.push(v);
            }
        }
    }

    const mapping = new Int32Array(N).fill(-1);
    const used = new Int8Array(geomVerts.length).fill(0);
    const bfsOrder = [];
    const visitedBFS = new Int8Array(N).fill(0);
    const qBFS = [0];
    visitedBFS[0] = 1;
    while (qBFS.length) {
        const u = qBFS.shift();
        bfsOrder.push(u);
        const nexts = [mapAPrime[u], mapB[u]];
        for (let v of nexts) {
            if (v !== undefined && parity[v] === 0 && !visitedBFS[v]) {
                visitedBFS[v] = 1;
                qBFS.push(v);
            }
        }
    }

    function solve(idx) {
        if (idx >= bfsOrder.length) return true;
        const u = bfsOrder[idx];
        const pa_prime = mapAPrime[u];
        const pb = mapB[u];
        let pb_rev = -1;
        for (let i = 0; i < N; i++) if (mapB[i] === u) { pb_rev = i; break; }

        let constraints = [];
        if (mapping[pa_prime] !== -1) constraints.push({ gIdx: mapping[pa_prime], isPent: false });
        if (mapping[pb] !== -1) constraints.push({ gIdx: mapping[pb], isPent: true });
        if (mapping[pb_rev] !== -1) constraints.push({ gIdx: mapping[pb_rev], isPent: true });

        let candidates = [];
        if (constraints.length === 0) {
            candidates = [0];
        } else {
            const first = constraints[0];
            const firstAdj = geomAdj[first.gIdx];
            for (let k = 0; k < firstAdj.length; k++) {
                const cand = firstAdj[k];
                if (used[cand]) continue;
                if (isPentagonal[first.gIdx][k] !== first.isPent) continue;
                let ok = true;
                for (let i = 1; i < constraints.length; i++) {
                    const c = constraints[i];
                    const edgeIdx = geomAdj[c.gIdx].indexOf(cand);
                    if (edgeIdx === -1 || isPentagonal[c.gIdx][edgeIdx] !== c.isPent) {
                        ok = false;
                        break;
                    }
                }
                if (ok) candidates.push(cand);
            }
        }

        for (let cand of candidates) {
            mapping[u] = cand;
            used[cand] = 1;
            if (solve(idx + 1)) return true;
            used[cand] = 0;
            mapping[u] = -1;
        }
        return false;
    }

    if (!solve(0)) {
        console.warn("S5 Layout isomorphism failed.");
        return null;
    }

    const output = new Array(N);
    const outerScale = 35;
    const innerScale = 22;
    for (let i = 0; i < N; i++) {
        if (parity[i] === 0) {
            const v = geomVerts[mapping[i]];
            output[i] = { fx: v.x * outerScale, fy: v.y * outerScale, fz: v.z * outerScale };
        } else {
            const h = mapA[i];
            const v = geomVerts[mapping[h]];
            output[i] = { fx: v.x * innerScale, fy: v.y * innerScale, fz: v.z * innerScale };
        }
    }
    return output;
}

// --------------------------------------------------
// A5 Truncated Icosahedron Layout
// --------------------------------------------------
function layoutA5(elements, multiplicationTable) {
    const phi = (1 + Math.sqrt(5)) / 2;
    const geomVerts = [];

    // 1. Generate 60 vertices
    const perms = [[0, 1, 2], [1, 2, 0], [2, 0, 1]]; // Even permutations of indices

    // Set 1: (0, +/-1, +/-3phi)
    const base1 = [0, 1, 3 * phi];
    perms.forEach(p => {
        const x_base = base1[p[0]];
        const y_base = base1[p[1]];
        const z_base = base1[p[2]];
        [1, -1].forEach(s1 => {
            [1, -1].forEach(s2 => {
                const v = { x: x_base, y: y_base, z: z_base };
                if (v.x === 0) { v.y *= s1; v.z *= s2; }
                else if (v.y === 0) { v.x *= s1; v.z *= s2; }
                else if (v.z === 0) { v.x *= s1; v.y *= s2; }
                geomVerts.push(v);
            });
        });
    });

    // Set 2: (+/-1, +/-(2+phi), +/-2phi)
    const base2 = [1, 2 + phi, 2 * phi];
    perms.forEach(p => {
        const x_base = base2[p[0]];
        const y_base = base2[p[1]];
        const z_base = base2[p[2]];
        [1, -1].forEach(sx => {
            [1, -1].forEach(sy => {
                [1, -1].forEach(sz => {
                    geomVerts.push({ x: x_base * sx, y: y_base * sy, z: z_base * sz });
                });
            });
        });
    });

    // Set 3: (+/-2, +/-(1+2phi), +/-phi)
    const base3 = [2, 1 + 2 * phi, phi];
    perms.forEach(p => {
        const x_base = base3[p[0]];
        const y_base = base3[p[1]];
        const z_base = base3[p[2]];
        [1, -1].forEach(sx => {
            [1, -1].forEach(sy => {
                [1, -1].forEach(sz => {
                    geomVerts.push({ x: x_base * sx, y: y_base * sy, z: z_base * sz });
                });
            });
        });
    });

    // 2. Build Adjacency and Classify Edges
    let minDistSq = Infinity;
    for (let i = 0; i < geomVerts.length; i++) {
        for (let j = i + 1; j < geomVerts.length; j++) {
            const d2 = Math.pow(geomVerts[i].x - geomVerts[j].x, 2) +
                Math.pow(geomVerts[i].y - geomVerts[j].y, 2) +
                Math.pow(geomVerts[i].z - geomVerts[j].z, 2);
            if (d2 < minDistSq) minDistSq = d2;
        }
    }

    const geomAdj = geomVerts.map(() => []);
    for (let i = 0; i < geomVerts.length; i++) {
        for (let j = 0; j < geomVerts.length; j++) {
            if (i === j) continue;
            const d2 = Math.pow(geomVerts[i].x - geomVerts[j].x, 2) +
                Math.pow(geomVerts[i].y - geomVerts[j].y, 2) +
                Math.pow(geomVerts[i].z - geomVerts[j].z, 2);
            if (Math.abs(d2 - minDistSq) < 0.1) {
                geomAdj[i].push(j);
            }
        }
    }

    // Helper to detect if an edge is part of a 5-cycle
    const isPentagonal = geomVerts.map(edges => new Array(geomAdj[geomVerts.indexOf(edges)].length).fill(false));

    function has5Cycle(u, v) {
        // Find if there is a path of length 4 from v back to u not using the direct edge
        const q = [{ node: v, path: [u, v] }];
        while (q.length > 0) {
            const { node, path } = q.shift();
            if (path.length === 5) {
                if (geomAdj[node].includes(u)) return true;
                continue;
            }
            for (let next of geomAdj[node]) {
                if (path.includes(next)) continue;
                q.push({ node: next, path: [...path, next] });
            }
        }
        return false;
    }

    for (let i = 0; i < geomVerts.length; i++) {
        for (let k = 0; k < geomAdj[i].length; k++) {
            if (has5Cycle(i, geomAdj[i][k])) {
                isPentagonal[i][k] = true;
            }
        }
    }

    // 3. Backtracking Solver
    const N = elements.length;
    const mapping = new Int32Array(N).fill(-1);
    const used = new Int8Array(geomVerts.length).fill(0);

    const mapA = multiplicationTable[0]; // Generator 'a' (order 2, hexagonal boundary)
    const mapB = multiplicationTable[1]; // Generator 'b' (order 5, pentagonal)

    const bfsOrder = [];
    const visited = new Int8Array(N).fill(0);
    const q = [0];
    visited[0] = 1;
    while (q.length) {
        const u = q.shift();
        bfsOrder.push(u);
        const nexts = [mapA[u], mapB[u]];
        for (let v of nexts) {
            if (!visited[v]) {
                visited[v] = 1;
                q.push(v);
            }
        }
    }

    function solve(idx) {
        if (idx >= N) return true;
        const u = bfsOrder[idx];

        // Find constraints from already mapped neighbors
        const pa = mapA[u];
        const pb = mapB[u];
        const pb_inv = elements.findIndex(el => {
            const b = currentElements[mapB[u]]; // This is wrong, mapB[u] is the index of the element
            // We need the index of x such that x * b = u
            return false; // placeholder
        });
        // Simpler: find pb_rev where mapB[pb_rev] === u
        let pb_rev = -1;
        for (let i = 0; i < N; i++) if (mapB[i] === u) { pb_rev = i; break; }

        let constraints = [];
        if (mapping[pa] !== -1) constraints.push({ gIdx: mapping[pa], isPent: false });
        if (mapping[pb] !== -1) constraints.push({ gIdx: mapping[pb], isPent: true });
        if (mapping[pb_rev] !== -1) constraints.push({ gIdx: mapping[pb_rev], isPent: true });

        let candidates = [];
        if (constraints.length === 0) {
            // Pick any start. (0, 1, 3phi)
            candidates = [0];
        } else {
            const first = constraints[0];
            for (let k = 0; k < geomAdj[first.gIdx].length; k++) {
                const cand = geomAdj[first.gIdx][k];
                if (used[cand]) continue;

                // Check if this edge matches constraint type
                if (isPentagonal[first.gIdx][k] !== first.isPent) continue;

                // Check other constraints
                let ok = true;
                for (let i = 1; i < constraints.length; i++) {
                    const c = constraints[i];
                    const edgeIdx = geomAdj[c.gIdx].indexOf(cand);
                    if (edgeIdx === -1 || isPentagonal[c.gIdx][edgeIdx] !== c.isPent) {
                        ok = false;
                        break;
                    }
                }
                if (ok) candidates.push(cand);
            }
        }

        for (let cand of candidates) {
            mapping[u] = cand;
            used[cand] = 1;
            if (solve(idx + 1)) return true;
            used[cand] = 0;
            mapping[u] = -1;
        }
        return false;
    }

    if (!solve(0)) {
        console.warn("A5 Layout isomorphism failed.");
        return null;
    }

    const output = new Array(N);
    const scale = 20;
    for (let i = 0; i < N; i++) {
        const v = geomVerts[mapping[i]];
        output[i] = { fx: v.x * scale, fy: v.y * scale, fz: v.z * scale };
    }
    return output;
}


// --------------------------------------------------
// Symbolic Labeling for Abstract Groups
// --------------------------------------------------

let currentSymbolicLabels = null;

function isPermutationGroup(key) {
    // S4, A4, S5, A5, S6 etc. stay as perms
    if ((key.startsWith('S') || key.startsWith('A')) && /^\d/.test(key.substring(1))) {
        return true;
    }
    return false;
}

function getSymbolicLabels(elements, table, genObjs) {
    const n = elements.length;
    const labels = new Array(n).fill(null);
    const words = new Array(n).fill(null);

    // Identify if Abelian to sort words
    const isAbelian = checkIfAbelian(table);

    labels[0] = "e"; // Use plain 'e' for dropdown compatibility
    words[0] = [];

    const queue = [0];
    const visited = new Set([0]);

    let head = 0;
    while (head < queue.length) {
        const u = queue[head++];
        genObjs.forEach((gen, gIdx) => {
            const v = table[gIdx][u];
            if (!visited.has(v)) {
                visited.add(v);
                words[v] = [...words[u], gIdx];
                queue.push(v);
            }
        });
    }

    for (let i = 1; i < n; i++) {
        let word = words[i];
        if (isAbelian) {
            word = [...word].sort((a, b) => a - b);
        }
        labels[i] = formatWord(word, genObjs);
    }
    return labels;
}

function checkIfAbelian(table) {
    const numGens = table.length;
    if (numGens < 2) return true;
    const numNodes = table[0].length;
    for (let i = 0; i < numGens; i++) {
        for (let j = i + 1; j < numGens; j++) {
            for (let k = 0; k < numNodes; k++) {
                if (table[i][table[j][k]] !== table[j][table[i][k]]) return false;
            }
        }
    }
    return true;
}

function formatWord(word, genObjs) {
    if (!word || word.length === 0) return "e";

    const parts = [];
    let currentGen = word[0];
    let count = 1;

    for (let i = 1; i <= word.length; i++) {
        if (i < word.length && word[i] === currentGen) {
            count++;
        } else {
            const label = genObjs[currentGen].label;
            if (count === 1) parts.push(label);
            else parts.push(`${label}${toSuperscript(count)}`);
            if (i < word.length) {
                currentGen = word[i];
                count = 1;
            }
        }
    }
    return parts.join('');
}





/**
 * If the group is a dihedral group D_n, returns an array of canonical labels
 * in the standard order: e, r, r², …, r^(n-1), s, rs, …, r^(n-1)s
 * where genObjs[0] is the rotation and genObjs[1] is the reflection.
 * Returns null if the group is not dihedral (under this generator ordering).
 *
 * table[gIdx][elemIdx] = index of (elem * gen[gIdx])  (right-multiplication)
 */
function getDihedralLabels(elements, table, genObjs) {
    const size = elements.length;
    if (genObjs.length !== 2 || size % 2 !== 0) return null;
    const n = size / 2;
    if (n < 2) return null;

    // Build powers of r: rPowers[k] = element index of r^k
    const rPowers = [0];
    let curr = table[0][0]; // identity * r = r
    for (let k = 1; k < n; k++) {
        rPowers.push(curr);
        curr = table[0][curr];
    }
    // Verify r has order exactly n
    if (curr !== 0) return null;

    const sElem = table[1][0]; // identity * s = s
    // Verify s² = e
    if (table[1][sElem] !== 0) return null;

    // Verify dihedral relation: s·r·s = r^{-1} = r^(n-1)
    const srElem = table[0][sElem];  // s * r
    const srsElem = table[1][srElem]; // s * r * s
    if (srsElem !== rPowers[n - 1]) return null;

    // Build canonical labels indexed by element index
    const labels = new Array(size).fill(null);
    for (let k = 0; k < n; k++) {
        labels[rPowers[k]] = formatWord(new Array(k).fill(0), genObjs);
    }
    for (let k = 0; k < n; k++) {
        labels[table[1][rPowers[k]]] = formatWord([...new Array(k).fill(0), 1], genObjs);
    }
    return labels;
}

/**
 * Returns an array of indices into `elements` in the canonical dihedral order:
 * e, r, r², …, r^{n-1}, s, rs, …, r^{n-1}s
 * Returns null if the group is not dihedral (same validation as getDihedralLabels).
 */
function getDihedralOrder(elements, table, genObjs) {
    const size = elements.length;
    if (genObjs.length !== 2 || size % 2 !== 0) return null;
    const n = size / 2;
    if (n < 2) return null;

    const rPowers = [0];
    let curr = table[0][0];
    for (let k = 1; k < n; k++) {
        rPowers.push(curr);
        curr = table[0][curr];
    }
    if (curr !== 0) return null;

    const sElem = table[1][0];
    if (table[1][sElem] !== 0) return null;

    const srElem = table[0][sElem];
    const srsElem = table[1][srElem];
    if (srsElem !== rPowers[n - 1]) return null;

    const order = [];
    for (let k = 0; k < n; k++) order.push(rPowers[k]);
    for (let k = 0; k < n; k++) order.push(table[1][rPowers[k]]);
    return order;
}

// Helper to compute conjugacy classes
function computeConjugacyClasses(elements) {
    const N = elements.length;
    const classes = [];
    const visited = new Array(N).fill(false);

    // Map elements to their string representation for quick lookup
    const elementToString = new Map(elements.map(e => [e.join(','), e]));
    const stringToElementIndex = new Map(elements.map((e, i) => [e.join(','), i]));

    for (let i = 0; i < N; i++) {
        if (visited[i]) continue;

        const currentClass = [];
        const x = elements[i]; // The representative of this class

        for (let j = 0; j < N; j++) {
            const g = elements[j];
            const g_inv = CayleyGraph.invertPerm(g);

            // Compute g * x * g_inv
            const gx = CayleyGraph.composePerm(g, x);
            const conjugate = CayleyGraph.composePerm(gx, g_inv);

            const conjugateStr = conjugate.join(',');
            const conjugateIdx = stringToElementIndex.get(conjugateStr);

            if (conjugateIdx !== undefined && !visited[conjugateIdx]) {
                currentClass.push(conjugateIdx);
                visited[conjugateIdx] = true;
            }
        }
        classes.push(currentClass);
    }
    return classes;
}

function generateHSLColors(count) {
    const colors = [];
    for (let i = 0; i < count; i++) {
        // Space out hues evenly
        const hue = (i * 360) / count;
        // Vary saturation and lightness slightly for even more distinction if count is high
        const saturation = 70 + (i % 2) * 20; // Toggle 70% and 90%
        const lightness = 50 + (i % 3) * 10;   // Variations in lightness
        colors.push(`hsl(${hue}, ${saturation}%, ${lightness}%)`);
    }
    return colors;
}

function updateConjugacyLegend(classes, elements) {
    const legendEl = document.getElementById('conjugacy-legend');
    if (!legendEl) return;

    legendEl.innerHTML = '';

    // Check if Abelian
    let isAbelian = true;
    for (let i = 0; i < elements.length; i++) {
        const classIdx = classes.findIndex(cls => cls.includes(i));
        if (classes[classIdx].length > 1) {
            isAbelian = false;
            break;
        }
    }

    if (isAbelian) {
        legendEl.innerHTML = '<div style="font-style: italic; color: #94a3b8;">Abelian Group: Each element is in its own conjugacy class.</div>';
        return;
    }

    const colors = generateHSLColors(classes.length);
    classes.forEach((currentClass, idx) => {
        const item = document.createElement('div');
        item.style.display = 'flex';
        item.style.alignItems = 'center';
        item.style.gap = '8px';
        item.style.marginBottom = '4px';

        const colorBox = document.createElement('div');
        colorBox.style.width = '12px';
        colorBox.style.height = '12px';
        colorBox.style.borderRadius = '2px';
        colorBox.style.backgroundColor = idx === 0 ? '#e2e8f0' : colors[idx];

        const text = document.createElement('span');
        const repIdx = currentClass[0];
        const repStr = currentSymbolicLabels
            ? currentSymbolicLabels[repIdx]
            : CayleyGraph.permToCycleString(elements[repIdx]);
        text.innerHTML = `Size ${currentClass.length}: <b>${repStr}</b>`;

        item.appendChild(colorBox);
        item.appendChild(text);
        legendEl.appendChild(item);
    });
}

let currentMultiplicationTable = null;
let currentElements = null;
let currentConjugacyClasses = null;
let currentGenObjs = null;
let currentCanonicalOrder = null; // Dihedral canonical element order [idx into currentElements]

function loadGroup(key) {
    const groupDef = groups[key];

    if (!groupDef) return;

    descEl.innerHTML = groupDef.desc;

    // Show Generators Section
    const genSection = document.getElementById('generators-section');
    if (genSection) genSection.style.display = 'block';

    // Prepare Data
    const basePerms = groupDef.baseGenerators ? groupDef.baseGenerators.map(g => g.p) : groupDef.generators.map(g => g.p);
    const gemPerms = groupDef.generators.map(g => g.p); // Visible generators
    const options = {
        serialize: (p) => p.join(','),
        identity: CayleyGraph.identityPerm(basePerms[0].length)
    };

    let { elements, multiplicationTable } = CayleyGraph.generateSubgroup(basePerms, options);
    currentElements = elements;

    // If baseGenerators are provided, only map the edges for the visible generators
    if (groupDef.baseGenerators) {
        const { composePerm } = CayleyGraph;
        const serialize = options.serialize;
        const elIdxMap = new Map(elements.map((el, i) => [serialize(el), i]));

        multiplicationTable = gemPerms.map(gen => {
            const table = {};
            elements.forEach((el, i) => {
                const prod = composePerm(el, gen);
                table[i] = elIdxMap.get(serialize(prod));
            });
            return table;
        });
    }

    currentMultiplicationTable = multiplicationTable;

    currentGenObjs = groupDef.generators.map((g, i) => ({
        permutation: g.p,
        label: g.label,
        color: g.color
    }));

    // Pre-compute symbolic labels if not a permutation group
    if (!isPermutationGroup(key)) {
        const dihedralLabels = getDihedralLabels(elements, multiplicationTable, currentGenObjs);
        currentSymbolicLabels = dihedralLabels ||
            CayleyGraph.getSymbolicLabels(elements, multiplicationTable, currentGenObjs);
        currentCanonicalOrder = dihedralLabels
            ? getDihedralOrder(elements, multiplicationTable, currentGenObjs)
            : null;
    } else {
        currentSymbolicLabels = null;
        currentCanonicalOrder = null;
    }

    // Show/hide Cayley Table button for non-permutation groups
    const cayleyTableBtn = document.getElementById('toggle-cayley-table');
    if (cayleyTableBtn) {
        cayleyTableBtn.style.display = isPermutationGroup(key) ? 'none' : 'block';
    }

    // Reset Conjugacy Toggle
    const toggleConjugacy = document.getElementById('toggle-conjugacy');
    if (toggleConjugacy) {
        toggleConjugacy.classList.remove('active');
        toggleConjugacy.textContent = "Show Conjugacy Classes";
    }
    document.getElementById('conjugacy-legend-section').style.display = 'none';

    // Compute conjugacy classes
    currentConjugacyClasses = computeConjugacyClasses(elements);
    updateConjugacyLegend(currentConjugacyClasses, elements);

    // Update Legend (Move to start for robustness)
    legendEl.innerHTML = '';
    currentGenObjs.forEach(g => {
        const div = document.createElement('div');
        div.className = 'legend-item';
        div.style.alignItems = 'flex-start';
        div.style.marginBottom = '12px';

        div.innerHTML = `
            <span class="color-box" style="background:${g.color}; margin-top: 4px;"></span>
            <div style="display: flex; flex-direction: column;">
                <span style="font-weight: 500; font-size: 0.9rem;">${g.label}</span>
            </div>
        `;
        legendEl.appendChild(div);
    });

    // --- Subgroup and Coset Logic ---
    const subgroupSelect = document.getElementById('subgroup-select');

    // 1. Compute all subgroups generated by one or two elements
    const subgroups = [];
    const subgroupStrings = new Set();

    function addSubgroup(subElements, generators) {
        if (subElements.length === 0) return;

        // Use a canonical string (sorted indices) to represent the subgroup
        // First map elements to their indices in the full group
        const elementToIndex = new Map();
        elements.forEach((el, idx) => elementToIndex.set(el.join(','), idx));

        const indices = subElements.map(el => elementToIndex.get(el.join(','))).sort((a, b) => a - b);
        const canon = indices.join(',');

        if (subgroupStrings.has(canon)) return;
        subgroupStrings.add(canon);

        // Identify structure
        const subTable = CayleyGraph.generateCayleyTable(subElements, options).table;
        const structure = CayleyGraph.identifyStructure(subElements, subTable, options);

        let genName = "";
        // reuse elementToIndex from above

        if (generators.length === 1) {
            const idx = elementToIndex.get(generators[0].join(','));
            const label = currentSymbolicLabels ? currentSymbolicLabels[idx] : CayleyGraph.permToCycleString(generators[0]);
            genName = `⟨${label}⟩`;
        } else {
            const labels = generators.map(g => {
                const idx = elementToIndex.get(g.join(','));
                return currentSymbolicLabels ? currentSymbolicLabels[idx] : CayleyGraph.permToCycleString(g);
            });
            genName = `⟨${labels.join(', ')}⟩`;
        }

        subgroups.push({
            name: `${structure} ${genName}`,
            elements: subElements
        });
    }

    // Always add the trivial subgroup
    addSubgroup([elements[0]], []);

    // 1-generator subgroups (Cyclic)
    for (let i = 1; i < elements.length; i++) {
        const sub = CayleyGraph.generateSubgroup([elements[i]], options).elements;
        addSubgroup(sub, [elements[i]]);
    }

    // 2-generator subgroups
    // We limit this for performance if the group is large
    const maxN = elements.length > 120 ? 0 : elements.length; // Don't do 2-gen for S5/S6 automatically? 
    // Actually, S5 is 120, S6 is 720. 
    // For S5 (order 120), n^2/2 = 7200 pairs. Manageable.
    // For S6 (order 720), n^2/2 = 250,000 pairs. Too many for blocking JS main thread.

    if (maxN > 0 && maxN <= 120) {
        for (let i = 1; i < elements.length; i++) {
            for (let j = i + 1; j < elements.length; j++) {
                const sub = CayleyGraph.generateSubgroup([elements[i], elements[j]], options).elements;
                addSubgroup(sub, [elements[i], elements[j]]);
            }
        }
    }

    // Sort subgroups by size
    subgroups.sort((a, b) => a.elements.length - b.elements.length);

    // Populate dropdown if it's the first time or group changed
    // We need to keep track of the current group to not rebuild the dropdown if the user just changed the subgroup
    if (!subgroupSelect.dataset.currentGroup || subgroupSelect.dataset.currentGroup !== key) {
        subgroupSelect.innerHTML = '<option value="none">None (Default Colors)</option>';
        subgroups.forEach((sg, index) => {
            if (sg.elements.length >= 1 && sg.elements.length < elements.length) {
                const opt = document.createElement('option');
                opt.value = index;
                opt.textContent = sg.name;
                if (sg.elements.length === 1) {
                    opt.textContent = "Trivial Subgroup {e}";
                }
                subgroupSelect.appendChild(opt);
            }
        });
        subgroupSelect.dataset.currentGroup = key;

        // Remove old listener if exists to prevent duplicates, then add new one
        const newSelect = subgroupSelect.cloneNode(true);
        subgroupSelect.parentNode.replaceChild(newSelect, subgroupSelect);
        newSelect.addEventListener('change', updateGraph);
    }

    // Call updateGraph to render the new group
    updateGraph();
}

function updateGraph() {
    if (!currentElements || !currentMultiplicationTable || !currentGenObjs) {
        console.warn("No group loaded. Cannot update graph.");
        return;
    }

    const key = selector.value;
    const formatFn = (p, idx) => {
        if (currentSymbolicLabels && idx !== undefined) return currentSymbolicLabels[idx];
        return CayleyGraph.permToCycleString(p);
    };

    const options = {
        formatLabel: formatFn
    };

    // Get selected subgroup
    const activeSubgroupSelect = document.getElementById('subgroup-select');
    const selectedSubgroupIndex = activeSubgroupSelect.value;

    // RULE: If a subgroup is selected, hide conjugacy classes
    if (selectedSubgroupIndex !== "none") {
        const toggleConjugacyBtn = document.getElementById('toggle-conjugacy');
        if (toggleConjugacyBtn && toggleConjugacyBtn.classList.contains('active')) {
            toggleConjugacyBtn.classList.remove('active');
            toggleConjugacyBtn.textContent = "Show Conjugacy Classes";
            // The isConjugacyActive check below will now be false
        }
    }

    let nodeColors = null;

    if (selectedSubgroupIndex !== "none") {
        // Re-compute subgroups based on currentElements (already loaded)
        const subgroups = [];
        const subgroupStrings = new Set();

        function addSubgroup(subElements, generators) {
            if (subElements.length === 0) return;
            const elementToIndex = new Map();
            currentElements.forEach((el, idx) => elementToIndex.set(el.join(','), idx));
            const indices = subElements.map(el => elementToIndex.get(el.join(','))).sort((a, b) => a - b);
            const canon = indices.join(',');
            if (subgroupStrings.has(canon)) return;
            subgroupStrings.add(canon);
            const subTable = CayleyGraph.generateCayleyTable(subElements, options).table;
            const structure = CayleyGraph.identifyStructure(subElements, subTable, options);
            let genName = "";
            if (generators.length === 1) {
                genName = `⟨${CayleyGraph.permToCycleString(generators[0])}⟩`;
            } else {
                genName = `⟨${generators.map(g => CayleyGraph.permToCycleString(g)).join(', ')}⟩`;
            }
            subgroups.push({
                name: `${structure} ${genName}`,
                elements: subElements
            });
        }

        addSubgroup([currentElements[0]], []);
        for (let i = 1; i < currentElements.length; i++) {
            const sub = CayleyGraph.generateSubgroup([currentElements[i]], options).elements;
            addSubgroup(sub, [currentElements[i]]);
        }
        const maxN = currentElements.length > 120 ? 0 : currentElements.length;
        if (maxN > 0 && maxN <= 120) {
            for (let i = 1; i < currentElements.length; i++) {
                for (let j = i + 1; j < currentElements.length; j++) {
                    const sub = CayleyGraph.generateSubgroup([currentElements[i], currentElements[j]], options).elements;
                    addSubgroup(sub, [currentElements[i], currentElements[j]]);
                }
            }
        }
        subgroups.sort((a, b) => a.elements.length - b.elements.length);

        const sg = subgroups[parseInt(selectedSubgroupIndex)];
        if (sg) {
            // Compute left cosets: gH
            const cosets = [];
            const remaining = new Set(currentElements.map(e => e.join(',')));

            while (remaining.size > 0) {
                // Get a representative
                const repStr = remaining.values().next().value;
                const rep = currentElements.find(e => e.join(',') === repStr);

                const coset = [];
                for (const h of sg.elements) {
                    const gh = CayleyGraph.composePerm(rep, h);
                    const ghStr = gh.join(',');
                    if (remaining.has(ghStr)) {
                        remaining.delete(ghStr);
                        coset.push(ghStr);
                    }
                }
                cosets.push(coset);
            }

            // Assign colors to cosets
            const cosetColors = [
                '#e2e8f0', // Coset 0 (Subgroup itself) - Light Gray
                '#f87171', // Red
                '#fbbf24', // Amber
                '#34d399', // Emerald
                '#60a5fa', // Blue
                '#a78bfa', // Purple
                '#f472b6', // Pink
                '#fb923c', // Orange
                '#2dd4bf', // Teal
                '#818cf8', // Indigo
                '#a3e635', // Lime
                '#facc15'  // Yellow
            ];

            nodeColors = new Array(currentElements.length);
            for (let i = 0; i < currentElements.length; i++) {
                const elStr = currentElements[i].join(',');
                const cosetIndex = cosets.findIndex(c => c.includes(elStr));
                nodeColors[i] = cosetColors[cosetIndex % cosetColors.length];
            }
        }
    }

    const isConjugacyActive = document.getElementById('toggle-conjugacy').classList.contains('active');
    const conjugacyLegendSection = document.getElementById('conjugacy-legend-section');
    if (conjugacyLegendSection) {
        conjugacyLegendSection.style.display = isConjugacyActive ? 'block' : 'none';
    }

    if (isConjugacyActive && currentConjugacyClasses) {
        nodeColors = nodeColors || new Array(currentElements.length);
        const classCount = currentConjugacyClasses.length;
        const generatedColors = generateHSLColors(classCount);

        currentConjugacyClasses.forEach((cls, idx) => {
            // Identity is usually the first class found (idx 0)
            const color = idx === 0 ? '#e2e8f0' : generatedColors[idx];
            cls.forEach(nodeIdx => {
                nodeColors[nodeIdx] = color;
            });
        });
    }

    options.nodeColors = nodeColors;


    // Geometric seed positions (used as initial x/y/z, not pinned fx/fy/fz)
    // chargeStrength: lower magnitude = stays closer to seed shape
    let fixedPositions = null;
    let surfaceType = null;
    let chargeStrength = -120; // default for purely free layouts
    if (key === "C2xC2xC2") {
        fixedPositions = layoutHypercube(currentElements, currentMultiplicationTable).map(p => ({ ...p, fz: p.fz }));
        chargeStrength = -5;
    } else if (key === "C2xC2xC2xC2") {
        fixedPositions = layoutHypercube(currentElements, currentMultiplicationTable);
        chargeStrength = 0;
    } else if (key === "C2xC4") {
        fixedPositions = layoutC2xC4(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "A4_Truncated") {
        fixedPositions = layoutTruncatedTetrahedron(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "S4_TruncatedCube") {
        fixedPositions = layoutTruncatedCube(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "S4_Permutohedron") {
        fixedPositions = layoutPermutohedron(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "S4_Type4") {
        fixedPositions = layoutNauru(currentElements, currentMultiplicationTable);
        chargeStrength = 0;
    } else if (key === "S5") {
        fixedPositions = layoutS5(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "A5") {
        fixedPositions = layoutA5(currentElements, currentMultiplicationTable);
        chargeStrength = -30;
    } else if (key === "C10xC5") {
        fixedPositions = layoutTorus(currentElements, currentMultiplicationTable, 10, 5);
        chargeStrength = -30;
        surfaceType = 'torus';
    }
    options.chargeStrength = chargeStrength;

    // Attempt 3D Render
    if (window.ForceGraph3D) {
        // Add layout type to options
        options.layoutType = key;
        render3DCayleyGraph(container, currentElements, currentMultiplicationTable, currentGenObjs, options, fixedPositions, surfaceType);
    } else {
        // Fallback to 2D
        console.warn("3d-force-graph not detected. Falling back to 2D.");
        if (graph3DContainer) graph3DContainer.style.display = 'none';
        if (graph3DBackground) graph3DBackground.style.display = 'none';
        fallbackCanvas.style.display = 'block';

        const W = fallbackCanvas.width;
        const H = fallbackCanvas.height;

        const layout = CayleyGraph.layoutCayleyGraph(currentElements.length, currentMultiplicationTable, W, H);
        const genLabels = currentGenObjs.map(g => g.label);
        const genColors = currentGenObjs.map(g => g.color);

        CayleyGraph.renderCayleyGraph(
            fallbackCanvas,
            currentElements,
            currentMultiplicationTable,
            genLabels,
            genColors,
            CayleyGraph.permToCycleString,
            layout.positions,
            { scale: 1, x: 0, y: 0 },
            options.nodeColors // Pass node colors to 2D render
        );
    }


}

function render3DCayleyGraph(parent, elements, multiplicationTable, generators, options = {}, fixedPositions = null, surfaceType = null) {
    if (!window.ForceGraph3D) {
        return;
    }

    const { formatLabel, nodeColors } = options;
    const format = formatLabel || (p => JSON.stringify(p));

    // 1. Prepare Nodes
    const nodes = elements.map((el, i) => {
        let labelText = format(el, i);

        // Add conjugacy class info if available and active
        const isConjugacyActive = document.getElementById('toggle-conjugacy').classList.contains('active');
        if (isConjugacyActive && currentConjugacyClasses) {
            const classIdx = currentConjugacyClasses.findIndex(cls => cls.includes(i));
            if (classIdx !== -1) {
                const classSize = currentConjugacyClasses[classIdx].length;
                labelText += `<br><span style="color: #a855f7; font-size: 0.85em;">Conjugacy Class Size: ${classSize}</span>`;
            }
        }

        const base = {
            id: i,
            label: `<div style="font-size: 1.2rem; padding: 4px; line-height: 1.4;">${labelText}</div>`,
            isIdentity: i === 0,
            val: i === 0 ? 2 : 1
        };

        if (nodeColors) {
            base.color = nodeColors[i];
        }
        // Seed initial positions from geometric layout (x/y/z = starting point, not pinned)
        if (fixedPositions && fixedPositions[i]) {
            base.x = fixedPositions[i].fx;
            base.y = fixedPositions[i].fy;
            base.z = fixedPositions[i].fz;

            // If requested, pin the nodes exactly to these positions
            if (options.chargeStrength === 0) {
                base.fx = fixedPositions[i].fx;
                base.fy = fixedPositions[i].fy;
                base.fz = fixedPositions[i].fz;
            }
        }
        return base;
    });

    // 2. Prepare Links
    const links = [];

    generators.forEach((gen, gIndex) => {
        const color = gen.color || '#ccc';
        const map = multiplicationTable[gIndex];

        let isOrder2 = true;
        for (let i = 0; i < elements.length; i++) {
            if (map[map[i]] !== i) {
                isOrder2 = false;
                break;
            }
        }

        for (let i = 0; i < elements.length; i++) {
            const source = i;
            const target = map[i];

            if (isOrder2) {
                if (source <= target) {
                    links.push({
                        source: source,
                        target: target,
                        color: color,
                        label: gen.label,
                        isUndirected: true
                    });
                }
            } else {
                links.push({
                    source: source,
                    target: target,
                    color: color,
                    label: gen.label,
                    isUndirected: false
                });
            }
        }
    });

    // 3. Render
    const container = setup3DContainer(parent);
    if (fallbackCanvas) fallbackCanvas.style.display = 'none';
    if (graph3DBackground) graph3DBackground.style.display = 'block';
    container.style.display = 'block';

    if (!graph3DInstance) {
        graph3DInstance = ForceGraph3D()(container)
            .backgroundColor('#0f172a')
            .nodeLabel('label')
            .nodeColor(node => node.color ? node.color : (node.isIdentity ? '#fbbf24' : '#38bdf8'))
            .nodeVal('val')
            .linkColor('color')
            .linkWidth(1.5)
            .linkOpacity(0.4)
            .linkDirectionalArrowLength(d => d.isUndirected ? 0 : 3.5)
            .linkDirectionalArrowRelPos(1)
            .nodeResolution(16);
    }

    // Straight edges
    graph3DInstance.linkCurvature(0).linkCurveRotation(0);

    // Apply a global gravity for disconnected graphs to pull components together
    const currentGroupDef = options.layoutType && typeof groups !== 'undefined' ? groups[options.layoutType] : null;
    if (currentGroupDef && currentGroupDef.baseGenerators) {
        function centerGravityForce(strength) {
            let n;
            function f(alpha) {
                if (!n) return;
                for (let i = 0; i < n.length; i++) {
                    n[i].vx += -n[i].x * alpha * strength;
                    n[i].vy += -n[i].y * alpha * strength;
                    n[i].vz += (n[i].z ? -n[i].z : 0) * alpha * strength;
                }
            }
            f.initialize = function (_) { n = _; };
            return f;
        }
        graph3DInstance.d3Force('centerGravity', centerGravityForce(0.01));
    } else {
        graph3DInstance.d3Force('centerGravity', null);
    }

    graph3DInstance.graphData({ nodes, links });

    // Custom Mesh (Torus or Cylinder)
    const scene = graph3DInstance.scene();

    // Cleanup previous mesh
    if (graph3DInstance.__customMesh) {
        scene.remove(graph3DInstance.__customMesh);
        graph3DInstance.__customMesh = null;
    }

    if (surfaceType && window.THREE) {
        let geometry, material;

        if (surfaceType === 'torus') {
            geometry = new THREE.TorusGeometry(80, 25, 16, 50);
            material = new THREE.MeshBasicMaterial({
                color: 0x555555,
                wireframe: true,
                opacity: 0.2,
                transparent: true
            });
        } else if (surfaceType === 'cylinder') {
            // LayoutTorus uses R=90, H=40 (+/- 40 means height 80)
            // CylinderGeometry(radiusTop, radiusBottom, height, radialSegments, heightSegments, openEnded)
            geometry = new THREE.CylinderGeometry(90, 90, 80, 32, 1, true);

            // Align Cylinder to Z axis? 
            // THREE.CylinderGeometry is aligned with Y axis by default.
            // Our layout uses Z for height. So we need to rotate the mesh.
            // Rotate 90 deg around X? 
            // fx, fy are circle (XY plane), fz is height.
            // So Cylinder axis is Z.
            // Default Cylinder is Y-axis. 
            // Rotate X by PI/2.

            material = new THREE.MeshBasicMaterial({
                color: 0x555555,
                wireframe: true,
                opacity: 0.15,
                transparent: true,
                side: THREE.DoubleSide
            });
        }

        if (geometry && material) {
            const mesh = new THREE.Mesh(geometry, material);
            if (surfaceType === 'cylinder') {
                mesh.rotation.x = Math.PI / 2;
            }
            scene.add(mesh);
            graph3DInstance.__customMesh = mesh;
        }
    }

    // Seeded groups use a gentle charge so they drift only slightly from their geometric layout;
    // unseeded groups (e.g. D4) use the standard charge for a natural force layout.
    const charge = options.chargeStrength !== undefined ? options.chargeStrength : (fixedPositions ? -30 : -120);
    graph3DInstance.d3Force('charge').strength(charge);
    graph3DInstance.numDimensions(3);

    // On desktop, offset the graph so it's centred in the area to the right of the panel
    requestAnimationFrame(() => {
        if (window.innerWidth > 640) {
            const panelW = 310;
            graph3DInstance.width(window.innerWidth - panelW);
            const container = setup3DContainer(parent);
            container.style.left = panelW + 'px';
            container.style.width = (window.innerWidth - panelW) + 'px';
        }
    });

    // Adjust camera for torus/cylinder view
    if (surfaceType === 'torus' || surfaceType === 'cylinder') {
        graph3DInstance.cameraPosition({ x: 150, y: 150, z: 150 });
    } else if (currentGroupDef && currentGroupDef.baseGenerators) {
        // Zoom out further to ensure all disconnected components stay in view
        graph3DInstance.cameraPosition({ x: 0, y: 0, z: 500 });
    } else {
        const n = elements.length;
        let zPos = 250;
        if (n >= 700) zPos = 1200; // E.g., S6
        else if (n >= 100) zPos = 600;  // E.g., S5
        else if (n >= 50) zPos = 350;   // E.g., A5

        graph3DInstance.cameraPosition({ x: 0, y: 0, z: zPos });
    }
}


selector.addEventListener('change', () => loadGroup(selector.value));

// Defer initial render until the tab is visible to avoid the force simulation
// collapsing all nodes to the centre when the page loads in a background tab.
let initialLoadPending = false;

function triggerInitialLoad() {
    loadGroup(selector.value);
    initialLoadPending = false;
}

window.addEventListener('load', () => {
    if (document.hidden) {
        initialLoadPending = true;
    } else {
        triggerInitialLoad();
    }
});

document.addEventListener('visibilitychange', () => {
    if (!document.hidden && initialLoadPending) {
        triggerInitialLoad();
    }
});

// Toggle Conjugacy Classes Button
const toggleConjugacyBtn = document.getElementById('toggle-conjugacy');
if (toggleConjugacyBtn) {
    toggleConjugacyBtn.addEventListener('click', () => {
        toggleConjugacyBtn.classList.toggle('active');
        const isActive = toggleConjugacyBtn.classList.contains('active');
        toggleConjugacyBtn.textContent = isActive ? "Hide Conjugacy Classes" : "Show Conjugacy Classes";

        // RULE: If we are showing conjugacy classes, reset subgroup selection to None
        if (isActive) {
            const subgroupSelect = document.getElementById('subgroup-select');
            if (subgroupSelect) {
                subgroupSelect.value = "none";
            }
        }

        updateGraph();
    });
}

// Reset Camera Button
const resetCameraBtn = document.getElementById('reset-camera');
if (resetCameraBtn) {
    resetCameraBtn.addEventListener('click', () => {
        if (!graph3DInstance) return;

        const key = selector.value;
        let surfaceType = null;
        if (key === "S4_Type5") surfaceType = null; // 2D Column Layout
        // Note: S4_Type4 is 2D, surfaceType null.

        // Use same coordinates as in render3DCayleyGraph
        if (surfaceType === 'torus' || surfaceType === 'cylinder') {
            graph3DInstance.cameraPosition(
                { x: 150, y: 150, z: 150 }, // Position
                { x: 0, y: 0, z: 0 },       // LookAt
                1000                        // Transition ms
            );
        } else { // This covers 'cylinder' and default cases
            graph3DInstance.cameraPosition(
                { x: 0, y: 0, z: 250 },     // Position
                { x: 0, y: 0, z: 0 },       // LookAt
                1000                        // Transition ms
            );
        }
    });
}

// --------------------------------------------------
// TikZ Export Logic
// --------------------------------------------------

function colorToTikZ(color) {
    if (!color) return "black";
    if (color.startsWith('#')) return color.substring(1);
    
    // Handle HSL or other formats by using a temporary element
    const temp = document.createElement('div');
    temp.style.color = color;
    document.body.appendChild(temp);
    const rgb = window.getComputedStyle(temp).color;
    document.body.removeChild(temp);
    
    const match = rgb.match(/\d+/g);
    if (!match) return "000000";
    return match.slice(0, 3).map(x => parseInt(x).toString(16).padStart(2, '0')).join('').toUpperCase();
}

function showToast(message) {
    const toast = document.getElementById('toast');
    if (!toast) return;
    toast.textContent = message;
    toast.classList.add('show');
    setTimeout(() => {
        toast.classList.remove('show');
    }, 3000);
}

function exportToTikZ() {
    if (!graph3DInstance) {
        showToast("3D Graph not initialized.");
        return;
    }

    const { nodes, links } = graph3DInstance.graphData();
    if (!nodes || nodes.length === 0) {
        showToast("No data to export.");
        return;
    }

    let tikz = "% TikZ Export from Cayley Graph Explorer\n";
    tikz += "% Requirement: \\usepackage{tikz}\n";
    tikz += "\\begin{tikzpicture}[scale=0.08, line join=round, line cap=round, x={(1cm,0cm)}, y={(0cm,1cm)}, z={(-0.5cm,-0.5cm)}]\n";

    // Define colors
    const colorMap = new Map();
    const definedColors = new Set();

    function defineTikZColor(color) {
        const hex = colorToTikZ(color);
        const name = "c" + hex;
        if (!definedColors.has(name)) {
            tikz += "  \\definecolor{" + name + "}{HTML}{" + hex + "}\n";
            definedColors.add(name);
        }
        return name;
    }

    tikz += "\n  % Edges\n";
    links.forEach(link => {
        const source = nodes.find(n => (n.id === (link.source.id ?? link.source)));
        const target = nodes.find(n => (n.id === (link.target.id ?? link.target)));
        if (!source || !target) return;

        const colorName = defineTikZColor(link.color || "#cccccc");
        const arrow = link.isUndirected ? "-" : "-stealth";
        
        tikz += "  \\draw[" + colorName + ", " + arrow + ", very thick] (" + source.x.toFixed(2) + ", " + source.y.toFixed(2) + ", " + source.z.toFixed(2) + ") -- (" + target.x.toFixed(2) + ", " + target.y.toFixed(2) + ", " + target.z.toFixed(2) + ");\n";
    });

    tikz += "\n  % Nodes\n";
    nodes.forEach(node => {
        const color = node.color || (node.isIdentity ? "#fbbf24" : "#38bdf8");
        const colorName = defineTikZColor(color);
        tikz += "  \\shade[ball color=" + colorName + "] (" + node.x.toFixed(2) + ", " + node.y.toFixed(2) + ", " + node.z.toFixed(2) + ") circle (100pt);\n";
    });

    tikz += "\\end{tikzpicture}\n";

    function fallbackCopyToClipboard(text) {
        const textArea = document.createElement("textarea");
        textArea.value = text;
        textArea.style.position = "fixed";
        textArea.style.left = "-9999px";
        textArea.style.top = "0";
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        try {
            const successful = document.execCommand('copy');
            if (successful) showToast("TikZ code copied to clipboard!");
            else showToast("Unable to copy TikZ code.");
        } catch (err) {
            console.error("Fallback copy failed:", err);
            showToast("Failed to copy. See console.");
        }
        document.body.removeChild(textArea);
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(tikz).then(() => {
            showToast("TikZ code copied to clipboard!");
        }).catch(err => {
            console.error("Clipboard API failed, trying fallback:", err);
            fallbackCopyToClipboard(tikz);
        });
    } else {
        fallbackCopyToClipboard(tikz);
    }
}

window.addEventListener('keydown', (e) => {
    if (e.ctrlKey && e.shiftKey && e.code === 'KeyX') {
        e.preventDefault();
        exportToTikZ();
    }
});
